# Ex No 1

# Ex No 1.a: Basic NumPy Array Operations

Aim: To understand the basics of NumPy arrays, including creation, attributes, slicing and indexing.

Scenario: You are a financial analyst working with a dataset of monthly sales revenue for a company over a year. You need to organize and analyze this data efficiently.

Sample Dataset:
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500]

Task to be Performed:
1.	Create a NumPy array from the sales revenue list.
2.	Retrieve the attributes of the array (shape, size, dtype).
3.	Slice the array to get the sales revenue for the first half of the year.
4.	Index the array to get the sales revenue for May.
5.	Calculate the total sales revenue for the year.
6.	Find the month with the highest sales revenue.

Expected Output:

Shape: (12,)

Size: 12

Data type: int32

First half of the year sales revenue: [12000 15000 17000 13000 16000 18000]

Sales revenue for May: 16000

Total sales revenue for the year: 195500

Month with highest sales revenue: July

In [4]:
import numpy as np
import pandas as pd

# 1.Create a NumPy array from the sales revenue list
months = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
sales_revenue = [12000, 15000, 17000, 13000, 16000, 18000, 20000, 19000, 17500, 16000, 15000, 16500]
month=np.array(months)
sales=np.array(sales_revenue)

# 2.Retrieve the attributes of the array (shape, size, dtype).
print("FOR THE MONTHS ARRAY")
print("Shape:",month.shape)
print("Dtype:",month.dtype)
print("Size:",month.size)

FOR THE MONTHS ARRAY
Shape: (12,)
Dtype: <U9
Size: 12


In [5]:
print("FOR THE SALES ARRAY")
print("Shape:",sales.shape)
print("Dtype:",sales.dtype)
print("Size:",sales.size)

FOR THE SALES ARRAY
Shape: (12,)
Dtype: int32
Size: 12


In [8]:
# 3.Slice the array to get the sales revenue for the first half of the year.
print(sales[:6])

[12000 15000 17000 13000 16000 18000]


In [10]:
# 4.ndex the array to get the sales revenue for May. 
print(sales[4])

16000


In [11]:
# 5.Calculate the total sales revenue for the year.
print(np.sum(sales))

195000


In [13]:
# 6.Find the month with the highest sales revenue.
print(month[np.argmax(sales)])

July


# Ex. No. 1.b: Aggregate Functions

Aim:
To use aggregate functions in NumPy for summarizing and analyzing data.

Scenario:
You are a financial analyst examining the monthly returns of different investment portfolios. You need to calculate various aggregate statistics to understand the performance and risk associated with each portfolio.

Sample Dataset:
returns_data = {
    'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01],
    'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04],
    'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05]
}

Task to be Performed:

1.	Create a NumPy array for each portfolio's returns.
2.	Calculate the total return for each portfolio over the six months.
3.	Calculate the mean monthly return for each portfolio.
4.	Find the portfolio with the highest mean return.
5.	Calculate the overall average return across all portfolios.
6.	Determine the variance and standard deviation of the returns for each portfolio to assess risk.


In [14]:
# 1.Create a NumPy array for each portfolio's returns.
returns_data = { 'portfolio_A': [0.05, 0.02, 0.04, 0.03, 0.06, 0.01], 'portfolio_B': [0.04, 0.03, 0.05, 0.02, 0.01, 0.04], 'portfolio_C': [0.03, 0.01, 0.02, 0.03, 0.04, 0.05] }
port_a=np.array(returns_data['portfolio_A'])
port_b=np.array(returns_data['portfolio_B'])
port_c=np.array(returns_data['portfolio_C'])
print(port_a)
print(port_b)
print(port_c)

[0.05 0.02 0.04 0.03 0.06 0.01]
[0.04 0.03 0.05 0.02 0.01 0.04]
[0.03 0.01 0.02 0.03 0.04 0.05]


In [25]:
# 2.Calculate the total return for each portfolio over the six months.
print("TOTAL RETURN OVER EACH PORTFOLIOS")
print(f"Portfolio A : {np.sum(port_a):.3f}")
print(f"Portfolio B : {np.sum(port_b):.3f}")
print(f"Portfolio C : {np.sum(port_c)}")

TOTAL RETURN OVER EACH PORTFOLIOS
Portfolio A : 0.210
Portfolio B : 0.190
Portfolio C : 0.18


In [26]:
# 3.Calculate the mean monthly return for each portfolio.
print(f"Portfolio A : {np.mean(port_a):.3f}")
print(f"Portfolio B : {np.mean(port_b):.3f}")
print(f"Portfolio C : {np.mean(port_c):.3f}")

Portfolio A : 0.035
Portfolio B : 0.032
Portfolio C : 0.030


In [29]:
# 4.Find the portfolio with the highest mean return.
l=[]
l.append(np.mean(port_a))
l.append(np.mean(port_b))
l.append(np.mean(port_c))
index=np.argmax(np.array(l))
if(index==0):
    print("Portfolio A has the highest mean")
elif index==1:
    print("Portfolio B has the highest mean")
else:
    print("Portfolio C has the highest mean")


Portfolio A has the highest mean


In [30]:
# 5.Calculate the overall average return across all portfolios.
print(f"Overall Average Return : {(np.sum(port_a)+np.sum(port_b)+np.sum(port_c))/3:.3f}")

Overall Average Return : 0.193


In [31]:
# 6.Determine the variance and standard deviation of the returns for each portfolio to assess risk.
print("STD AND VARIANCE OVER EACH PORTFOLIOS")
print("For Portfolio A")
print(f"Standard Deviation : {np.std(port_a):.3f}")
print(f"Variance : {np.var(port_a):.3f}")
print("For Portfolio B")
print(f"Standard Deviation : {np.std(port_b):.3f}")
print(f"Variance : {np.var(port_b):.3f}")
print("For Portfolio C")
print(f"Standard Deviation : {np.std(port_c):.3f}")
print(f"Variance : {np.var(port_c):.3f}")


STD AND VARIANCE OVER EACH PORTFOLIOS
For Portfolio A
Standard Deviation : 0.017
Variance : 0.000
For Portfolio B
Standard Deviation : 0.013
Variance : 0.000
For Portfolio C
Standard Deviation : 0.013
Variance : 0.000


# Ex No 1.c: Splitting and Aggregation
Aim: 
To practice slicing, indexing, splitting, and aggregating Numpy arrays.

Scenario: 
You are analysing the monthly rainfall data of a region for a year. You need to extract specific information for analysis, including quarterly splits and total rainfall for each quarter.

Sample Dataset:
rainfall_data = [120, 85, 90, 110, 95, 100, 105, 85, 115, 130, 125, 140]

Task to be Performed:

1.	Create a Numpy array from the given rainfall data.
2.	Slice the array to get the rainfall data for the first quarter (January to March).
3.	Index the array to get the rainfall data for July.
4.	Split the array into four quarters and print each quarter's data.
5.	Calculate and print the total rainfall for each quarter and also print the month with the highest rainfall in each month

Expected Output:

1.	First Quarter Rainfall Data: [120 85 90] 

2.	Rainfall for July: 105 

3.	First Quarter Rainfall Data: [120  85  90]
    Second Quarter Rainfall Data: [110  95 100]
    Third Quarter Rainfall Data: [105  85 115]
    Fourth Quarter Rainfall Data: [130 125 140].

4.	Total Rainfall for First Quarter: 295 

    Month with highest rainfall in First Quarter: Month 1 with 120 

    Total Rainfall for Second Quarter: 305 

    Month with highest rainfall in Second Quarter: Month 1 with 110 

    Total Rainfall for Third Quarter: 305 

    Month with highest rainfall in Third Quarter: Month 3 with 115 

    Total Rainfall for Fourth Quarter: 395 
    
    Month with highest rainfall in Fourth Quarter: Month 3 with 140 


In [3]:
# Create a Numpy array from the given rainfall data.
import numpy as np
rainfall_data = [120, 85, 90, 110, 95, 100, 105, 85, 115, 130, 125, 140]
rainfall=np.array(rainfall_data)
print(rainfall)

[120  85  90 110  95 100 105  85 115 130 125 140]


In [5]:
# Slice the array to get the rainfall data for the first quarter (January to March).
print(f"First Quarter Rainfall Data: {rainfall[:3]}")

First Quarter Rainfall Data: [120  85  90]


In [6]:
# Index the array to get the rainfall data for July.
print(f"Rainfall for July: {rainfall[6]}")

Rainfall for July: 105


In [10]:
# Split the array into four quarters and print each quarter's data.
print(f"First Quarter Rainfall Data: {rainfall[:3]}")
print(f"Second Quarter Rainfall Data: {rainfall[3:6]}")
print(f"Third Quarter Rainfall Data: {rainfall[6:9]}")
print(f"Fourth Quarter Rainfall Data: {rainfall[9:]}")

First Quarter Rainfall Data: [120  85  90]
Second Quarter Rainfall Data: [110  95 100]
Third Quarter Rainfall Data: [105  85 115]
Fourth Quarter Rainfall Data: [130 125 140]


In [20]:
# Calculate and print the total rainfall for each quarter and also print the month with the highest rainfall in each month
print(f"Total Rainfall for first quarter : {np.sum(rainfall[:3])}")
print(f"Month with highest rainfall in first quarter : Month {np.argmax(rainfall[:3])+1} with {rainfall[np.argmax(rainfall[:3])]}")
print(f"total Rainfall for second quarter : {np.sum(rainfall[3:6])}")
print(f"Month with highest rainfall in second quarter : Month {np.argmax(rainfall[3:6])+1} with {rainfall[np.argmax(rainfall[3:6])+3]}")
print(f"total Rainfall for third quarter : {np.sum(rainfall[6:9])}")
print(f"Month with highest rainfall in third quarter : Month {np.argmax(rainfall[6:9])+1} with {rainfall[np.argmax(rainfall[6:9])+6]}")
print(f"total Rainfall for fouth quarter : {np.sum(rainfall[9:])}")
print(f"Month with highest rainfall in fourth quarter : Month {np.argmax(rainfall[9:])+1} with {rainfall[np.argmax(rainfall[9:])+9]}")


Total Rainfall for first quarter : 295
Month with highest rainfall in first quarter : Month 1 with 120
total Rainfall for second quarter : 305
Month with highest rainfall in second quarter : Month 1 with 110
total Rainfall for third quarter : 305
Month with highest rainfall in third quarter : Month 3 with 115
total Rainfall for fouth quarter : 395
Month with highest rainfall in fourth quarter : Month 3 with 140
